USE [master]
GO

/****** Object:  Database [yugioh]    Script Date: 15/10/2022 03:52:14 ******/
DROP DATABASE [yugioh]
GO

/****** Object:  Database [yugioh]    Script Date: 15/10/2022 03:52:14 ******/
CREATE DATABASE [yugioh]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'yugioh', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\yugioh.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'yugioh_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\yugioh_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [yugioh].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [yugioh] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [yugioh] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [yugioh] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [yugioh] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [yugioh] SET ARITHABORT OFF 
GO

ALTER DATABASE [yugioh] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [yugioh] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [yugioh] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [yugioh] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [yugioh] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [yugioh] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [yugioh] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [yugioh] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [yugioh] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [yugioh] SET  DISABLE_BROKER 
GO

ALTER DATABASE [yugioh] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [yugioh] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [yugioh] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [yugioh] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [yugioh] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [yugioh] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [yugioh] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [yugioh] SET RECOVERY FULL 
GO

ALTER DATABASE [yugioh] SET  MULTI_USER 
GO

ALTER DATABASE [yugioh] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [yugioh] SET DB_CHAINING OFF 
GO

ALTER DATABASE [yugioh] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [yugioh] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [yugioh] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [yugioh] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [yugioh] SET QUERY_STORE = OFF
GO

ALTER DATABASE [yugioh] SET  READ_WRITE 
GO

